services:
  php:
    env_file:
      - ./.docker/.env.local
    volumes:
      - ~/.composer:/var/www/.composer
    networks:
      - magebit

  xdebug:
    env_file:
      - ./.docker/.env.local
    volumes:
      - ~/.composer:/var/www/.composer
    networks:
      - magebit

  nginx:
    env_file:
      - ./.docker/.env.local
    networks:
      - magebit

  varnish:
    labels:
      - traefik.enable=true
      - traefik.http.routers.hyva-course.tls=true
      - traefik.http.routers.hyva-course.entrypoints=https
      - traefik.http.routers.hyva-course.rule=Host(`hyva-course.docker`)
      - traefik.http.services.hyva-course.loadbalancer.server.port=80
    networks:
      - magebit

  db:
    networks:
      magebit:
        aliases:
          - db.hyva-course.docker

  redis:
    networks:
      magebit:
        aliases:
          - redis.hyva-course.docker

  opensearch:
    labels:
      - traefik.enable=true
      - traefik.http.routers.hyva-course-es.tls=true
      - traefik.http.routers.hyva-course-es.entrypoints=https
      - traefik.http.routers.hyva-course-es.rule=Host(`es.hyva-course.docker`)
      - traefik.http.services.hyva-course-es.loadbalancer.server.port=9200
    networks:
      magebit:
        aliases:
          - es.hyva-course.docker

  node:
    networks:
      - magebit

  rabbitmq:
    networks:
      magebit:
        aliases:
          - rabbitmq.hyva-course.docker

networks:
  magebit:
    external: true
